version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


  cache:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: user_service
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      JWT_SECRET: "change_me"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: